config/routes.rb
Rails.application.routes.draw do
  get 'card_loan', to: 'cards#index'
  get 'search', to: 'cards#search'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :loan
  has_many :card_loan_methods
  has_many :loan_methods, through: :card_loan_methods
end

app/models/card_loan_method.rb
class CardLoanMethod < ApplicationRecord
  belongs_to :card
  belongs_to :loan_method
end

app/models/loan.rb
class Loan < ApplicationRecord
  has_many :cards
end

app/models/loan_method.rb
class LoanMethod < ApplicationRecord
  has_many :card_loan_methods
  has_many :cards, through: :card_loan_methods
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash.provider
    uid = auth_hash.uid
    name = auth_hash.info.name
    oauth_token = auth_hash.credentials.token
    oauth_expires_at = Time.at(auth_hash.credentials.expires_at)
    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
      user.oauth_token = oauth_token
      user.oauth_expires_at = oauth_expires_at
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
    rescue ActiveRecord::RecordNotFound
  end

  def authenticate
    return if logged_in?
    redirect_to card_loan_path
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @q = Card.ransack(params[:q])
    @cards = @q.result.includes(:loan_methods)
    @loans = Loan.all
    @loan_methods = LoanMethod.all
  end

  def search
    @q = Card.page(params[:page]).search(search_params)
    @cards = @q.result(distinct: true)
    @search_query = params[:q]
  end

  private

  def search_params
    params.require(:q).permit!
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to card_loan_path
  end
  def destroy
    session[:user_id] = nil
    redirect_to card_loan_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cards/_search_from.html.slim
= search_form_for(@q, url:search_path) do |f|
  p
    = f.label :name_cont, 'カード名'
    = f.search_field :name_cont
  p
    = f.label :loan_id_eq, '借入額'
    = radio_button_tag 'q[loan_id_eq]', ''
    = label_tag 'q_loan_id_eq_','指定なし'
    = f.collection_radio_buttons :loan_id_eq, @loans, :id, :amount
  p
    = f.label :loan_methods_id_in, '借入方法'
    /= f.collection_check_boxes :loan_methods_id_in, @loan_methods, :id, :method, include_hidden: false
    = f.collection_check_boxes :loan_methods_id_in, @loan_methods, :id, :method
  = f.submit

app/views/cards/index.html.slim
h1 Cards#index
= render 'search_from', q: @q, loan: @loans
table
  - @cards.each do |card|
    tr
      td
        = card.name
      td
        = card.info
      td
        = card.loan.amount
      td
        - card.loan_methods.each do |loan_method|
          = loan_method.method
          | ,

app/views/cards/search.html.slim
h1
  | Cards#search
p
  | 検索クエリ
  br
  - unless @search_query[:name_cont].empty?
    | カード名:
    = @search_query[:name_cont]
  br
  - unless @search_query[:loan_id_eq].empty?
    | 借入額:
    = Loan.find(@search_query[:loan_id_eq]).amount
  br
    - unless @search_query[:loan_methods_id_in].reject(&:blank?).empty?
      | 借入方法:
      - @search_query[:loan_methods_id_in].reject(&:blank?).each do |loan_method_id|
        = LoanMethod.find(loan_method_id).method
        |,

= page_entries_info @cards
table
  - @cards.each do |card|
    tr
      td
        = card.name
      td
        = card.info
= paginate @cards
= link_to 'トップ', card_loan_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | AffiliSample
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if logged_in?
      li = current_user.name
      li = link_to 'ログアウト', logout_path
    - else
      li = link_to 'Facebookでログイン', '/auth/facebook'
    = yield